#server:
#  port: 8080
#
#spring:
#  application:
#    name: gateway-service
#
#zuul:
#  routes:
#    user-service:
#      url: http://localhost:8090
#    track-service:
#      url: http://localhost:8070
#
#ribbon:
#  eureka:
#    enabled: false
#
